blank_issues_enabled: false

contact_links:
  - name: Nitrux Community Discussions
    url: https://github.com/orgs/Nitrux/discussions
    about: Please ask questions, share ideas, or discuss policies here.
